[package]
name = "hal"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.33"
libc = { version = "0.2", optional = true }

[features]
use_std = ["libc"]
default = []

[target.x86_64-unknown-none.dependencies]
x86_64 = { version = "0.15.4", features = ["memory_encryption"] }

[target.x86_64-unknown-uefi.dependencies]
x86_64 = { version = "0.15.4", features = ["memory_encryption"] }
uefi = "0.37.0"

[target.'cfg(target_os = "linux")'.dependencies]
x86_64 = { version = "0.15.4", features = ["memory_encryption"] }
syscalls = { version = "0.8.1", default-features = false }

[target.aarch64-unknown-uefi.dependencies]
uefi = "0.37.0"
aarch64-paging = { version = "0.12.1", default-features = false }
aarch64-cpu = "11.2.0"

[target.aarch64-unknown-none.dependencies]
aarch64-paging = { version = "0.12.1", default-features = false }
aarch64-cpu = "11.2.0"

